---
apiVersion: v1
kind: Namespace
metadata:
  name: <namespace-name>
---
apiVersion: v1
data:
  .dockerconfigjson: <base64-json>
kind: Secret
metadata:
  name: <docker-registry-secret-name>
  namespace: <namespace-name>
type: kubernetes.io/dockerconfigjson
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  name: <role-name>
rules:
- apiGroups:
  - extensions
  - policy
  resourceNames:
  - pks-privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <role-binding-name>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <role-name>
subjects:
- kind: ServiceAccount
  name: <service-account-name>
  namespace: <namespace-name>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <service-account-name>
  namespace: <namespace-name>
